### ISSUE TITLE
CREST endpoint documentation format

### ISSUE THREAD

**Issue by CarbonAlabel** [ccpgames/eveonline-third-party-documentation#228]
We should look into introducing a new documentation format for CREST endpoint pages. Currently, we just have newer pages imitating the format of previously written pages, resulting in a format (if it can even be called one) which is implemented very inconsistently. I'll base this on the format I used for documenting the fleet endpoints, and is currently only used for them.
### Top-level documentation categories

Pages should be organized into categories based on their general theme and functionality.
Currently, we have four categories: Character, Map, Eve, Fleet. Additional ones could be Corporation, Market, Remote UI...
### Multiple endpoints on a single page

I'd suggest keeping multiple endpoints on a single page only when they handle the same kind of resource, meaning that a collection and its corresponding resource should be on the same page, but different collections/resources should have their separate pages. I'd like to hear if anyone thinks there are certain endpoints which should be exceptions to this.
### Endpoint route

Instead of providing a URL with ID placeholders, which is not the way things should be done in CREST, we should provide directions for walking through endpoints to get the full URL.
I've opted for a JavaScript inspired syntax describing navigation within an endpoint, and arrows for indicating an HTTP request.
Also, for those who decide to go against best practices by hardcoding and building URLs themselves, an example URL should be provided, preferably the one of the sample response included.
### Sample responses/requests

For each endpoint and every method it supports, a sample request/response should be included, along with the exact content type of the included sample.
The samples should be pretty formatted, be valid JSON (no `{ ... }` placeholders) and use two spaces for indentation (Four or eight spaces take up a lot of horizontal width, which combined with many levels of indentation can ruin the reading experience, especially on mobile devices.)
If there are multiple versions available, only the latest one should be present. Deprecated versions shouldn't be documented.
### Response/request details

Every sample response/request should also have a section detailing properties of the sample. Not every property should be described, as many of them are self-evident and their descriptions wouldn't be much more than clutter.
### Notes and references

If there is any additional information relevant to the use of the endpoint, it should be placed in the notes section.
Any references (dev blogs, patch notes, forum posts...) should be listed at the bottom of the page, under a L2 References header.

That's it for my proposal. Consider #220 and changes in #227 to be the reference implementation of the format. If there are any question or suggestions, please comment here.

**Comment by timpanogos** [comment]
> Top-level documentation categories
> Pages should be organized into categories based on their general theme and functionality.
> Currently, we have four categories: Character, Map, Eve, Fleet. Additional ones could be Corporation, Market, Remote UI...

I think there should be two top level guides  one is a Programmers Guide and the second is a Technical Reference Guide.

The users guide should contain all of the common/generic information that pertains across all endpoints and/or groups of endpoints.  There should be an index in this section that is organized by functionality per carbon's suggestion.

The Technical Reference Guide should be the actual endpoint post, get, put and delete data formats.  It should have an index page laid out alphabetically based on the endpoint's name with indented links to the individual data structures UID's that endpoint supports.  There should be an individual page per unique UID.

> Multiple endpoints on a single page

Each "endpoint" has the potential of having four unique data structure UID's  (post, get, put, delete) As mentioned above, the Technical Reference Guide should have a unique .md page per unique UID.  Individual UID pages should conveniently link their sibling UID pages.


> Sample responses/requests

I disagree that the json should be valid and not contain ... only enough to show the pattern should be given.  Also a pseudo data structure is more important than the sample and should be provided above the sample.

The auto generated documentation I'm creating is based on Carbon's template.  We should declare a boilerplate template and agree on it before proceeding much further on this.

**Comment by timpanogos** [comment]
Proposed boiler plate templates:

The [Group page template](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/root/groupPage.md) page is typically an endpoint or a group of common endpoints page.  These are the pages that a Programmers Guide->Functionally grouped index would want to link to.

This template contains the $title which is the replacement macro that gets the human friendly name given to the endpoint.  The post, get, put and delete UID's are replaced with the UID's value.  The children of the group are automatically bullet item listed and linked to.  See [Group: Characters](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/root/characters/CharacterSearch.md) for an example.

The [leaf node template](https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/root/characters/contacts/ContactCreate.md) was patterned after Carbon's fleet examples.  This temple is heavy on the idea of leaving "(TBD)"  under all required labels for which values are not yet known, thus making it easy for other authors to quickly fill in information as it is determined.

The current autogen determines the titles, post, get, put and delete data UIDs, example url's and several of the cache times (all those not requiring id segments and/or authentication).

See the [auto-gened Technical Reference index page]( https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/root/technical.md).  Note some links are still broken.

**Comment by timpanogos** [comment]
Team,

With CCP being swamped with the current mobile work, it’s not likely for arbitration on this issue to happen anytime soon.  If nothing comes of my documentation auto-gen work I can only hope that what caused this push will become a priority for CREST.  I would just like to capture that cause here and note that the whole concept of the restructuring of the documentation was based on this cause.  The basic restructuring concept is to map the actual URL tree of all possible endpoints and their leaf mime type data structure definitions.  The “cause” spoken of above is the current lack of this information being available from CREST.

History of this PR ... 

I wanted to write a proper REST client that dynamically generated endpoint URL's and was able to identify if it's current implementation of versions of the mime identified structures were out of date.  

This was not possible to do with the existing GET/OPTIONS requests against the root endpoint.  This is not currently possible because only about one half of all of the endpoints (which I have been able to identify) are being reported.

I needed my own static structure to identify/compare my current implementation version against that reported with a combination of a GET request on the root and OPTIONS requests on each of the reported endpoints of the GET request.  (BTW the X-DEPRECATED header is broken; I’ll write a bug on this soonish).  Thus I filled in the holes of missing data from the get of the root with what I discovered from other sources and browsing around the namespace.

Now that I assume I have a full list of all possible endpoints and their possible post, get, put and delete mime types it is easy for me to kick out two things:

1.	A json object graph of what I would expect to get from an HTTP get request to the root url.  See [sisi-root-endpoints.json] (https://github.com/timpanogos/crestj/blob/master/crest-core/config/sisi-root-endpoints.json)
2.	 Auto-generated documentation based on group and leaf .md templates so as to identify what I have hard-coded as a static representation of the endpoint tree. Namely an endpoint name, endpoint url example, endpoint relative uri segment, post, get, put and delete mime types and version,  tree relationships to other endpoints and mime types (i.e. groups, but more, full URL map),  some cache times (could do all with more effort).  See [auto-gened Technical Reference index page]( https://github.com/timpanogos/eveonline-third-party-documentation/blob/master/docs/crest/root/technical.md)

Thus my whole documentation push evolved from my desire/need to have a full URL mapping of all CREST endpoints for dynamic URL building in my client and realizing this would be a preferred method of also laying out the documentation, encouraging people to dynamically build their url’s and by the way, here is a url based map/index to all mime types currently in the tree.
